# Generated by Django 5.1.7 on 2026-05-27 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='God',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('portrait', models.ImageField(blank=True, null=True, upload_to='god_clicker/gods/')),
                ('base_cost', models.PositiveIntegerField(default=10)),
                ('favor_per_click_bonus', models.PositiveIntegerField(default=1)),
                ('favor_per_second', models.PositiveIntegerField(default=0)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GodClickerPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favor', models.BigIntegerField(default=0)),
                ('total_clicks', models.BigIntegerField(default=0)),
                ('favor_per_click', models.PositiveIntegerField(default=1)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('gods', models.ManyToManyField(blank=True, related_name='worshippers', to='god_clicker.god')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='god_clicker_player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
