services:
  backend:
    build: ./backendHub
    ports:
      - "8000:8000"
    volumes:
        - ./backendHub/db.sqlite3:/app/db.sqlite3
        - ./backendHub/static:/app/static
        - ./backendHub/media:/app/media
    command: ./entrypoint.sh