services:
  nginx:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: ./nginx/prod.conf
        target: /etc/nginx/nginx.conf
        read_only: true
      - type: bind
        source: /etc/letsencrypt
        target: /etc/letsencrypt
        read_only: true
      - type: bind
        source: /var/www/certbot
        target: /var/www/certbot
        read_only: true
