services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
      - type: bind
        source: ./backendHub/static
        target: /static
        read_only: true
      - type: bind
        source: ./backendHub/media
        target: /media
        read_only: true
    depends_on:
      - backend

  backend:
    build: ./backendHub
    container_name: backend
    expose:
      - "8000"
    volumes:
      - type: bind
        source: ./backendHub
        target: /app
    command: ./entrypoint.sh
