# Generated by Django 5.1.7 on 2026-06-02 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GodPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faith', models.FloatField(default=0)),
                ('total_faith', models.FloatField(default=0)),
                ('click_power', models.FloatField(default=1)),
                ('generators', models.JSONField(blank=True, default=dict)),
                ('upgrades', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='godclicker_player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
