# Generated by Django 5.1.7 on 2026-06-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GodClicker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='godplayer',
            name='rebirths',
            field=models.IntegerField(default=0),
        ),
    ]
