# Generated by Django 5.1.7 on 2025-05-28 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Texture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('texture_img', models.ImageField(upload_to='Sledgepong/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('coins', models.IntegerField(default=0)),
                ('collection', models.ManyToManyField(blank=True, related_name='player_collections', to='Sledgepong.texture')),
                ('curtexture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_texture', to='Sledgepong.texture')),
            ],
        ),
    ]
