# Generated by Django 5.1.7 on 2025-08-08 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sledgepong', '0002_remove_player_username_player_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='coins',
        ),
    ]
