# Generated by Django 5.1.7 on 2025-10-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sledgepong', '0004_alter_player_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('difficulty', models.CharField(choices=[('not_applicable', 'N/A'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('blood_red', 'Blood Red'), ('red_hot', 'Red Hot'), ('white_hot', 'White Hot'), ('ash', 'Ash')], default='not_applicable', max_length=100)),
                ('duration', models.TimeField(blank=True, null=True)),
                ('level_data', models.JSONField()),
            ],
        ),
    ]
