# Generated by Django 5.1.7 on 2025-10-24 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sledgepong', '0005_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='artist',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='level',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='Sledgepong.player'),
        ),
        migrations.AddField(
            model_name='level',
            name='soundtrack',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
