# Generated by Django 5.1.7 on 2025-10-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sledgepong', '0006_level_artist_level_creator_level_soundtrack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
