# Generated by Django 5.2.7 on 2026-03-17 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sledgepong', '0007_alter_level_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=False)),
                ('plays', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('song_url', models.URLField(blank=True, null=True)),
                ('level_data', models.JSONField()),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_levels', to='Sledgepong.player')),
            ],
        ),
    ]
