worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile on;
    keepalive_timeout 65;

    upstream django {
        server backend:8000;  # docker-compose service name
    }

    server {
        listen 80;
        server_name daeaglehub.com www.daeaglehub.com 155.212.225.65;

        client_max_body_size 20M;

        location / {
            proxy_pass http://django;  # <-- MUST match upstream name
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /static/ {
            alias /static/;
            expires 30d;
            access_log off;
        }

        location /media/ {
            alias /media/;
            expires 30d;
            access_log off;
        }
    }
}
